[package]
name = "crabdropper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
winit = "0.28.3"
screenshots = "0.5.2"
image = { version = "0.24.5", default-features = false, features = ["png"] }
softbuffer = "0.2.0"
copypasta-ext = { version = "0.4.4", default-features = false, features = ["x11-bin", "wayland-bin"] }
termcolor = "1.2.0"
